schema_version = "1.0.0"

id = "smirk"
version = "0.4.1"
name = "SMIRK"
tagline = "Dynamically carve Facial Features into a mesh"
maintainer = "Krysidian"
type = "add-on"

website = "https://github.com/Krysidian/smirk"

tags = ["Animation", "Rigging", "Grease Pencil"]

blender_version_min = "5.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]
copyright = [
    "2024-2026 Krysidian",
]

[permissions]
network = "Need to sync motion-capture data to server"
files = "Import node groups from blend files/Import icon files from disk"


